* Clarinet

  This is a cli utility for the Clarity smart contract language.

** Requisites

   Rust tooling should be installed in advance. I recommend installing
   `cargo` through `rustup`. Also, as I am a Ubuntu user, the package
   `libssl-dev` should be installed as well in order to properly build
   `clarinet`.

** Installing

   Use the following commands:

   #+begin_src sh
     git clone https://github.com/hirosystems/clarinet --recursive
     cd clarinet
     cargo install --path . --locked
   #+end_src

** Usage

   Creates a new project called `my-project`:

   #+begin_src sh
   clarinet new my-project
   #+end_src

   Inside `my-project` folder:
   - creates a new contract called `bbtc`:
     #+begin_src sh
     clarinet contract new bbtc
     #+end_src
   - checks syntax of project's source files:
     #+begin_src sh
     clarinet check
     #+end_src
   - runs unit tests:
     #+begin_src sh
     clarinet test
     #+end_src
   - opens a repl:
     #+begin_src sh
     clarinet console
     #+end_src
   - creates a local offline blockchain environment for testing (Devnet):
     #+begin_src sh
     clarinet integrate
     #+end_src
     Not sure this exited as expected. Also, it messes up with the
     console it is opened in.


* Readings
** Characteristics and Risks of Standardized Options

*** Chapter 1

    - An option is the right either to buy or to sell a specified
      amount or value of a particular underlying interest at a fixed
      exercise price by exercising the option before its specified
      expiration date.
    - A call (put) option gives a right to buy (sell).
    - A physical delivery option to physically send or receive the
      underlying interest when the option is exercised.
    - A cash-settled option gives the right to receive a cash payment
      based on the difference between a determined value of the
      underlying interest at the time the option is exercised and the
      fixed exercise price of the option:
      - call: interest value at exercise exceeds the exercise price of
        the option.
      - put: interest value at exercise is less than the exercise
        price of the option.
    - Options having the same standardized terms are identical and
      comprise an options series.
    - Options that are traded on more than one options market at the
      same time are called multiply-traded options.
    - Options that are traded on a US options market and on a foreign
      options market are called internationally-traded options.

*** Chapter 2

    - The person who buys conveyed buy a certain option is called the
      option holder.
    - The part responsible for (if and when assigned an option
      exercise) to perform according to the terms of the option is
      called the option writer (or seller).
    - An option writer who has been assigned an exercise is called an
      assigned writer.
    - The price at which the option holder has the right either to
      purchase or to sell the underlying interest is known as the
      exercise price (or strike price).
    - An American-style option may be exercised at any time prior to
      its expiration.
    - A European-style option may be exercised only during a specified
      period before the option expires. These options are usually
      exercisable only on its expiration date.
    - A capped option will be automatically exercised prior to
      expiration if the options market on which the option is trading
      determines that the value of the underlying interest at a
      specified time on a trading day hits the cap price for the option.
    - The unit of trading (a.k.a contract size) of a physical delivery
      option is the amount of the underlying interest that is subject
      to being purchased or sold upon the exercise of a single option
      contract. It works as a multiplier for cash-settled options.
    - The cash settlement amount is the amount of cash that the holder
      of a cash-settled option is entitled to receive upon
      exericse. The currency in which this is payable is called the
      settlement currency.
    - The determination of whether to adjust outstanding options in
      response to a particular event, and, if so, what the adjustment
      should be, is made by a majority vote of an adjustment panel.
    - The premium is the price that the holder of an option pays and
      the writer of an option receives for the rights conveyed by the
      option. The currency in which this is payable is called the
      premium currency.
    - Opening transaction is a purchase or sale transaction by which a
      person establishes or increases a position as either the holder
      or the writer of an option.
    - Closing transaction is a transaction in which, at some point
      prior to expiration, the option holder makes an offseting sale
      of an identical option, or the option writer makes an offseting
      purchase of an identical option. A closing transaction in an
      option reduces or cancels out an investor's preivous position as
      the holder or the writer of that option. Transaction costs of
      closing transactions may be lower than the transaction costs of
      associated with exercises.
    - Combination positions are positions in more than one option at
      the same time:
      - a spread involves being both the buyer and writer of the same
        type of option on the same underlying interest, with the
        options having different exercise prices and/or expiration
        dates;
      - a straddle consists of purchasing or writing both a put and a
        call on the same underlying interest, with the options having
        the same exercise price and expiration date.
    - A person's position as the holder of an option is called long,
      whereas a person's position as the writer of an option is called
      short.
    - A covered call writer owns or acquires the amount of the
      underlying interest that is deliverable upon exercise of the
      call.
    - An option is said to be at the money when the current market
      value of the underlying interest is the same as the exercise
      price of the option.
    - A call (put) option is said to be in the money if the current
      market value of the underlying interest is above (below) the
      exercise price of the option.
    - A call (put) option is said to be out of the money if the
      current market value of the underlying interest is below (above)
      the exercise price of the option.
    - Intrinsic value reflects the amount, if any, by which an option
      is in the money. Time value is whatever the the premium of the
      option is in addition to its intrinsic value. Example: With the
      market price of XYZ stock at $45 a share, an XYZ 40 call may
      have a current market value of $6 a share, reflecting an
      intrinsic value of $5 a share and a time value of $1 a share.
    - The cap interval is a constant established by the options market
      on which a series of capped options is traded.
    - The exercise price for a capped-style call (put) option plus
      (minus) is the cap price for the option.
    - The cash settlement amount is the cash amount that the holder of
      a cash-settled capped option is entitled to receive upon the
      exercise of the option.
*** Chapter 3

    - Each stock option generally covers 100 shares of the underlying
      security.
    - No adjustment is made for ordinary cash dividends or
      distribution. A cash dividend or distribution will be considered
      ordinary unless it exceeds 10% of the aggregate market value of
      the underlying security outstanding.
    - As such, covered writers of calls are entitled to retain
      dividends and distributions earned on the underlying securities
      during the time prior to exercise. However, a call holder
      becomes entitled to the dividend if he exercises the option
      prior to the ex-dividend date even though the assigned writer
      may not be notified that he was assigned an exercise until after
      the ex-date.
    - Stock splits can result in an adjustment in the number of
      underlying shares or the exercise price, or both. However, when
      a stock distribution results in the issuance of one or more
      whole shares of stock for each outstanding share, the number of
      outstanding options is proportionately increased and the
      exercise price is proportionately decreased.
    - Adjustments in exercise prices are rounded to the nearest 1/8 of
      a dollar, and adjustments in the number of underlying shares are
      rounded down to eliminate fractional shares.
    - Property distribution example: if XYZ spins off its subsidiary
      ABC by distributing to its stockholders 2.5 shares of ABC stock
      for each share of XYZ stock, outstanding XYZ options might be
      adjusted to require delivery of 100 shares of XYZ stock plus 250
      shares of ABC stock.
    - Merger example: if XYZ is acquired by PQR in a merger where each
      holder of XYZ stock receives $50 plus 1/2 share of PQR stock for
      each shareof XYZ stock held, XYZ options might be adjusted to
      call for the delivery of $5,000 in cash and 50 shares of PQR
      stock instead of 100 shares of XYZ stock.
*** Chapter 8

    - An option holder who intends to exercise an option before
      expiration must give exercise instructions to his brokerage firm
      before the firm's cut-off time for accepting exercise
      instructions on the last trading day before expiration.

*** Chapter 10

    - An option holder runs the risk of losing the entire amount paid
      for the option in a relatively short period of time.
    - The more an option is out of money and the shorter the remaining
      time to expiration, the greater the risk that an option holder
      will lose all or part of his investment in the option.
    - Prior to the period when a European-style option or a capped
      option is exercisable, the only means through which the holder
      can realize value from the option (unless the capped option is
      automatically exercised) is to sell it at its then market price
      in an available secondary market.
    - The exercise provisions of an option may create certain risks
      for the option holders.
    - The courts, the SEC, another regulatory agency, OCC, or the
      options markets may impose exercise restrictions.
    - An option writer may be assigned an exercise at any time during
      the period the option is exercisable.
    - The writer of a covered call forgoes the opportunity to benefit
      from an increase in the value of the underlying interest above
      the option price, but continues to bear the risk of a decline in
      the value of the underlying interest.
    - The writer of an uncovered call is in an extremely risky
      position and may incur large losses if the value of the
      underlying interest increases above the exercise price.
    - As with writing uncovered calls, the risk of writing put options
      is substantial. The writer of a put option bears a risk of loss
      if the value of the underlying interest declines below the
      exercise price, and such loss could be substantial if the
      decline is significant.
    - The obligation of a writer of an uncovered call or of a put that
      is not cash-secured to meet applications margin requirements
      creates additional risks.
    - A sudden development may cause a sharp upward or downward spike
      in the value of the interest underlying a capped option.
    - Disruptions in markets for underlying interests could result in
      losses for options investors.

** Options as a Strategic Investment

*** Chapter 1

    - A stock option is the right to buy or sell a particular stock at
      a certain price limited period of time.
    - The stock in question is called the underlying security.
    - A call (put) option gives the owner the right to buy (sell) the
      underlying security.
    - The price at which the stock may be bought or sold is the
      exercise price (a.k.a striking price).
    - Four specifications uniquely describe any option contract:
      1. the type (put or call);
      2. the underlying security;
      3. the expiration date;
      4. the striking price.
    - An option is a wasting asset.
    - An option is a derivative security.
    - Striking prices are generally spaced 5 points apart for stocks,
      although for more expensive stocks, the striking prices may be
      10 points apart.
    - Options have expiration dates in one of three fixed cycles:
      1. the January/April/July/October cycle;
      2. the February/May/August/November cycle;
      3. the March/June/September/December cycle.
    - LEAPS are available on some stocks.
    - Options expire on the Saturday following the third Friday of the
      expiration month, although the third Friday is the last day of
      trading.
    - A class of options refers to all put and call contracts on the
      same underlying security.
    - A series consists of all contracts of the same class having the
      same expiration date and striking price.
    - An opening transaction is the initial transaction, either a buy
      or a sell. A closing transaction reduces the customer's
      position.
    - The difference between the number of opening and closing
      transactions in each option series is called the open interest.
    - An option is said to be trading at parity with the underlying if
      it is trading for its intrinsic value.
    - The major quantifiable factors influencing the price of an
      option are the:
      - price of the underlying stock;
      - striking price of the option itself;
      - time remaining until expiration of the option;
      - volatility of the underlying stock;
      - current risk-free interest rate;
      - dividend rate of the underlying stock.
    - When options are exercised prior to expiration, this is called
      early or premature exercise.
    - A LEAPS option is one that is very long-term, expiring one or
      more years hence.
    - Order information consists of:
      - whether the transaction is a buy or a sell;
      - the option to be bought or sold;
      - whether the trade is opening or closing a position;
      - whether the transaction is a spread;
      - the desired price.
    - There are some types of orders:
      - market order is an order to buy or sell the option at the best
        possible price as soon as the order gets to the exchange
        floor.
      - market not held order is an order tha gives the floor broker
        the right to use some judgment regarding the execution of the
        order, that is, it may stay still waiting for a better moment
        to execute it, but this also means that the outcome of such an
        order can be worse than a simple market order outcome.
      - limit order is an order to buy or to sell at a specified price.
      - stop order is an order that becomes a market order when the
        security trades at or through the price specified on the
        order. Buy stop orders are entered above the current market
        price and sell stop orders are placed below the current market
        price.
      - stop limit order is an order that becomes a limit order when
        the specified price is reached.

* Glossary

  | Name     | Description                  |
  |----------+------------------------------|
  | microSTX | 0.000001 STX                 |
  | STX      | Stacks coin/token            |
  | SEC      | ???                          |
  | OCC      | Options Clearing Corporation |
  | LEAP     | A kind of long-term option   |
  | NFT      | non fungible token           |
  
