[project]
name = "koku"
requirements = []
costs_version = 1

[contracts.amm]
path = "contracts/amm.clar"
depends_on = ["lp-token", "token"]

[contracts.custom-sip-010-trait]
path = "contracts/traits/custom-sip-010-trait.clar"
depends_on = []

[contracts.lp-token]
path = "contracts/lp-token.clar"
depends_on = ["owner-trait", "sip-010-trait-ft-standard", "custom-sip-010-trait"]

[contracts.owner-trait]
path = "contracts/traits/owner-trait.clar"
depends_on = []

[contracts.sft-trait]
path = "contracts/traits/sft-trait.clar"
depends_on = []

[contracts.sip-010-trait-ft-standard]
path = "contracts/traits/sip-010-trait-ft-standard.clar"
depends_on = []

[contracts.token]
path = "contracts/token.clar"
depends_on = ["sip-010-trait-ft-standard"]

[contracts.token-option]
path = "contracts/token-option.clar"
depends_on = []

[contracts.vault]
path = "contracts/vault.clar"
depends_on = ["owner-trait", "sip-010-trait-ft-standard", "lp-token", "token"]
