[project]
name = "koku"
requirements = []
costs_version = 1

[contracts.amm]
path = "contracts/amm.clar"
depends_on = []

[contracts.dyv-token]
path = "contracts/dyv-token.clar"
depends_on = ["sip-010-trait-ft-standard"]

[contracts.sip-010-trait-ft-standard]
path = "contracts/sip-010-trait-ft-standard.clar"
depends_on = []