[project]
name = "dy.finance"
requirements = []
costs_version = 1

[contracts.current-price]
path = "contracts/current-price.clar"
depends_on = []

[contracts.mint-trait]
path = "contracts/traits/mint-trait.clar"
depends_on = []

[contracts.burn-trait]
path = "contracts/traits/burn-trait.clar"
depends_on = []

[contracts.minting]
path = "contracts/minting.clar"
depends_on = ["token"]

[contracts.lp-token]
path = "contracts/lp-token.clar"
depends_on = ["owner-trait", "sip-010-trait-ft-standard", "mint-trait", "burn-trait"]

[contracts.owner-trait]
path = "contracts/traits/owner-trait.clar"
depends_on = []

[contracts.sip013-trait-sft-standard]
path = "contracts/traits/sip013-trait-sft-standard.clar"
depends_on = []

[contracts.sip-010-trait-ft-standard]
path = "contracts/traits/sip-010-trait-ft-standard.clar"
depends_on = []

[contracts.token]
path = "contracts/token.clar"
depends_on = ["sip-010-trait-ft-standard"]

[contracts.token-option]
path = "contracts/token-option.clar"
depends_on = ["sip013-trait-sft-standard", "sip-010-trait-ft-standard"]

[contracts.vault]
path = "contracts/vault.clar"
depends_on = ["owner-trait", "sip-010-trait-ft-standard", "lp-token", "token"]
