[project]
name = "dy.finance"
requirements = []
costs_version = 1

[contracts.current-price]
path = "contracts/current-price.clar"
depends_on = []

[contracts.mint-trait]
path = "contracts/traits/mint-trait.clar"
depends_on = []

[contracts.burn-trait]
path = "contracts/traits/burn-trait.clar"
depends_on = []

[contracts.epoch-convert]
path = "contracts/epoch-convert.clar"
depends_on = []

[contracts.hello]
path = "contracts/hello.clar"
depends_on = []

[contracts.owner-trait]
path = "contracts/traits/owner-trait.clar"
depends_on = []

[contracts.sip-010-trait-ft-standard]
path = "contracts/traits/sip-010-trait-ft-standard.clar"
depends_on = []

[contracts.sip013-trait-sft-standard]
path = "contracts/traits/sip013-trait-sft-standard.clar"
depends_on = []

[contracts.token]
path = "contracts/token.clar"
depends_on = ["sip-010-trait-ft-standard", "mint-trait", "burn-trait"]

[contracts.minting]
path = "contracts/minting.clar"
depends_on = ["token", "owner-trait"]

[contracts.fold-example]
path = "draft/fold-example.clar"
depends_on = ["owner-trait", "sip-010-trait-ft-standard", "token"]

[contracts.vault]
path = "contracts/vault.clar"
depends_on = ["owner-trait", "sip-010-trait-ft-standard", "token"]

[contracts.timestamp-vault]
path = "contracts/timestamp-vault.clar"
depends_on = ["owner-trait", "sip-010-trait-ft-standard", "token"]
