[project]
name = "koku"
requirements = []
costs_version = 1

[contracts.amm]
path = "contracts/amm.clar"
depends_on = []

[contracts.token]
path = "contracts/token.clar"
depends_on = ["sip-010-trait-ft-standard"]

[contracts.sip-010-trait-ft-standard]
path = "contracts/sip-010-trait-ft-standard.clar"
depends_on = []

[contracts.dyv-vault]
path = "contracts/dyv-vault.clar"
depends_on = ["owner-trait"]

[contracts.owner-trait]
path = "contracts/owner-trait.clar"
depends_on = []
