[project]
name = "liquidity-pool"
requirements = []
costs_version = 1
[contracts.liquidity-pool]
path = "contracts/liquidity-pool.clar"
depends_on = []

[contracts.sip-010-v0a]
path = "contracts/sip-010-v0a.clar"
depends_on = []
