[project]
name = "koku"
requirements = []
costs_version = 1

[contracts.liquidity-pool]
path = "draft/liquidity-pool.clar"
depends_on = ["sip-010-v0a", "liquidity-token"]

[contracts.liquidity-token]
path = "draft/liquidity-token.clar"
depends_on = ["sip-010-v0a"]

[contracts.sip-010-v0a]
path = "contracts/sip-010-v0a.clar"
depends_on = []

[contracts.token]
path = "contracts/token.clar"
depends_on = ["sip-010-v0a"]

[contracts.hello-world]
path = "contracts/hello-world.clar"
depends_on = []