[project]
name = "koku"
requirements = []
costs_version = 1

[contracts.sip-010-trait-ft-standard]
path = "contracts/sip-010-trait-ft-standard.clar"
depends_on = []

[contracts.token-v2]
path = "contracts/token-v2.clar"
depends_on = ["sip-010-trait-ft-standard"]

[contracts.minting]
path = "contracts/minting.clar"
depends_on = ["token-v2"]