#!/bin/sh

for test in test_pool/*.test.ts; do
    test_name=$(basename $test .test.ts)
    echo "running ${test_name}"
    log_output=$(./run_test $test_name)
    if [ "$?" -eq 0 ]
        then
            echo "test ${test_name} has run successfully"
        else
            echo "test ${test_name} has failed"
            echo "### log output ###"
            printf "${log_output}"
            echo ""
            exit 1
    fi
    sleep 50
done
