[project]
name = "sample-token"
requirements = []
costs_version = 1
[contracts.sip-010-v0a]
path = "contracts/sip-010-v0a.clar"
depends_on = []

[contracts.token]
path = "contracts/token.clar"
depends_on = ["sip-010-v0a"]
