name: Integration Test Workflow
on:
  workflow_run:
    workflows: [Unit Test Workflow]
    types:
      - completed
jobs:
  test:
    name: "Integration tests on private testnet"
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: "Execute tests"
        run: |
          cd integration
          npm install
          ./run_tests
