name: Integration
on: [push]
jobs:
  test:
    name: "Integration tests on private testnet"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Execute tests"
        run: |
          cd integration
          npm install
          ./run_test current-price
          sleep 20
          ./run_test events
